name: Build-push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  Build_Docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zz22ff/zerotier:latest
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
         push: true
         tags: zz22ff/zerotier:latest