name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

<<<<<<< HEAD
    runs-on: Ubantu-latest
=======
    runs-on: ubuntu-latest
>>>>>>> eb57ef0c72989658967728c855960d43df6c4468

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zz22ff/zerotier:latest
    - name: Login Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push Docker Image
      run: docker push zz22ff/zerotier:latest
